/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.showcase.elite.accountsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CreditLineDetails generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`credit_line_details`")
public class CreditLineDetails implements Serializable {

    private Integer id;
    private String month;
    private Integer expectedCredit;
    private Integer actualCredit;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`month`", nullable = true, length = 255)
    public String getMonth() {
        return this.month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    @Column(name = "`expected_credit`", nullable = true, scale = 0, precision = 10)
    public Integer getExpectedCredit() {
        return this.expectedCredit;
    }

    public void setExpectedCredit(Integer expectedCredit) {
        this.expectedCredit = expectedCredit;
    }

    @Column(name = "`actual_credit`", nullable = true, scale = 0, precision = 10)
    public Integer getActualCredit() {
        return this.actualCredit;
    }

    public void setActualCredit(Integer actualCredit) {
        this.actualCredit = actualCredit;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreditLineDetails)) return false;
        final CreditLineDetails creditLineDetails = (CreditLineDetails) o;
        return Objects.equals(getId(), creditLineDetails.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
