/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.showcase.elite.accountsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetAccountsSummaryByTypeResponse implements Serializable {


    @ColumnAlias("type")
    private String type;

    @ColumnAlias("netBalance")
    private BigInteger netBalance;

    @ColumnAlias("totalAccounts")
    private Long totalAccounts;

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public BigInteger getNetBalance() {
        return this.netBalance;
    }

    public void setNetBalance(BigInteger netBalance) {
        this.netBalance = netBalance;
    }

    public Long getTotalAccounts() {
        return this.totalAccounts;
    }

    public void setTotalAccounts(Long totalAccounts) {
        this.totalAccounts = totalAccounts;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetAccountsSummaryByTypeResponse)) return false;
        final GetAccountsSummaryByTypeResponse getAccountsSummaryByTypeResponse = (GetAccountsSummaryByTypeResponse) o;
        return Objects.equals(getType(), getAccountsSummaryByTypeResponse.getType()) &&
                Objects.equals(getNetBalance(), getAccountsSummaryByTypeResponse.getNetBalance()) &&
                Objects.equals(getTotalAccounts(), getAccountsSummaryByTypeResponse.getTotalAccounts());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getType(),
                getNetBalance(),
                getTotalAccounts());
    }
}
