/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.showcase.elite.accountsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetFrequentTransactionsResponse implements Serializable {


    @ColumnAlias("total_transactions")
    private Long totalTransactions;

    @ColumnAlias("last_transaction_date")
    private Date lastTransactionDate;

    @ColumnAlias("first_transaction_date")
    private Date firstTransactionDate;

    @ColumnAlias("average_transaction_amount")
    private Double averageTransactionAmount;

    @ColumnAlias("transaction_status_id")
    private Long transactionStatusId;

    @ColumnAlias("transaction_type_id")
    private Long transactionTypeId;

    public Long getTotalTransactions() {
        return this.totalTransactions;
    }

    public void setTotalTransactions(Long totalTransactions) {
        this.totalTransactions = totalTransactions;
    }

    public Date getLastTransactionDate() {
        return this.lastTransactionDate;
    }

    public void setLastTransactionDate(Date lastTransactionDate) {
        this.lastTransactionDate = lastTransactionDate;
    }

    public Date getFirstTransactionDate() {
        return this.firstTransactionDate;
    }

    public void setFirstTransactionDate(Date firstTransactionDate) {
        this.firstTransactionDate = firstTransactionDate;
    }

    public Double getAverageTransactionAmount() {
        return this.averageTransactionAmount;
    }

    public void setAverageTransactionAmount(Double averageTransactionAmount) {
        this.averageTransactionAmount = averageTransactionAmount;
    }

    public Long getTransactionStatusId() {
        return this.transactionStatusId;
    }

    public void setTransactionStatusId(Long transactionStatusId) {
        this.transactionStatusId = transactionStatusId;
    }

    public Long getTransactionTypeId() {
        return this.transactionTypeId;
    }

    public void setTransactionTypeId(Long transactionTypeId) {
        this.transactionTypeId = transactionTypeId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetFrequentTransactionsResponse)) return false;
        final GetFrequentTransactionsResponse getFrequentTransactionsResponse = (GetFrequentTransactionsResponse) o;
        return Objects.equals(getTotalTransactions(), getFrequentTransactionsResponse.getTotalTransactions()) &&
                Objects.equals(getLastTransactionDate(), getFrequentTransactionsResponse.getLastTransactionDate()) &&
                Objects.equals(getFirstTransactionDate(), getFrequentTransactionsResponse.getFirstTransactionDate()) &&
                Objects.equals(getAverageTransactionAmount(), getFrequentTransactionsResponse.getAverageTransactionAmount()) &&
                Objects.equals(getTransactionStatusId(), getFrequentTransactionsResponse.getTransactionStatusId()) &&
                Objects.equals(getTransactionTypeId(), getFrequentTransactionsResponse.getTransactionTypeId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTotalTransactions(),
                getLastTransactionDate(),
                getFirstTransactionDate(),
                getAverageTransactionAmount(),
                getTransactionStatusId(),
                getTransactionTypeId());
    }
}
