/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.showcase.elite.accountsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetMostFrequentTransactionsResponse implements Serializable {


    @ColumnAlias("id")
    private Long id;

    @ColumnAlias("date")
    private Date date;

    @ColumnAlias("payment_method_id")
    private Long paymentMethodId;

    @ColumnAlias("source_account_id")
    private Long sourceAccountId;

    @ColumnAlias("benericiary_id")
    private Long benericiaryId;

    @ColumnAlias("amount")
    private Long amount;

    @ColumnAlias("description")
    private String description;

    @ColumnAlias("corporate_ref_no")
    private String corporateRefNo;

    @ColumnAlias("transaction_status_id")
    private Long transactionStatusId;

    @ColumnAlias("transaction_type_id")
    private Long transactionTypeId;

    @ColumnAlias("payment_instruction")
    private String paymentInstruction;

    @ColumnAlias("accountName")
    private String accountName;

    @ColumnAlias("beneficiaryName")
    private String beneficiaryName;

    @ColumnAlias("transaction_count")
    private Long transactionCount;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Long getPaymentMethodId() {
        return this.paymentMethodId;
    }

    public void setPaymentMethodId(Long paymentMethodId) {
        this.paymentMethodId = paymentMethodId;
    }

    public Long getSourceAccountId() {
        return this.sourceAccountId;
    }

    public void setSourceAccountId(Long sourceAccountId) {
        this.sourceAccountId = sourceAccountId;
    }

    public Long getBenericiaryId() {
        return this.benericiaryId;
    }

    public void setBenericiaryId(Long benericiaryId) {
        this.benericiaryId = benericiaryId;
    }

    public Long getAmount() {
        return this.amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCorporateRefNo() {
        return this.corporateRefNo;
    }

    public void setCorporateRefNo(String corporateRefNo) {
        this.corporateRefNo = corporateRefNo;
    }

    public Long getTransactionStatusId() {
        return this.transactionStatusId;
    }

    public void setTransactionStatusId(Long transactionStatusId) {
        this.transactionStatusId = transactionStatusId;
    }

    public Long getTransactionTypeId() {
        return this.transactionTypeId;
    }

    public void setTransactionTypeId(Long transactionTypeId) {
        this.transactionTypeId = transactionTypeId;
    }

    public String getPaymentInstruction() {
        return this.paymentInstruction;
    }

    public void setPaymentInstruction(String paymentInstruction) {
        this.paymentInstruction = paymentInstruction;
    }

    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public String getBeneficiaryName() {
        return this.beneficiaryName;
    }

    public void setBeneficiaryName(String beneficiaryName) {
        this.beneficiaryName = beneficiaryName;
    }

    public Long getTransactionCount() {
        return this.transactionCount;
    }

    public void setTransactionCount(Long transactionCount) {
        this.transactionCount = transactionCount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetMostFrequentTransactionsResponse)) return false;
        final GetMostFrequentTransactionsResponse getMostFrequentTransactionsResponse = (GetMostFrequentTransactionsResponse) o;
        return Objects.equals(getId(), getMostFrequentTransactionsResponse.getId()) &&
                Objects.equals(getDate(), getMostFrequentTransactionsResponse.getDate()) &&
                Objects.equals(getPaymentMethodId(), getMostFrequentTransactionsResponse.getPaymentMethodId()) &&
                Objects.equals(getSourceAccountId(), getMostFrequentTransactionsResponse.getSourceAccountId()) &&
                Objects.equals(getBenericiaryId(), getMostFrequentTransactionsResponse.getBenericiaryId()) &&
                Objects.equals(getAmount(), getMostFrequentTransactionsResponse.getAmount()) &&
                Objects.equals(getDescription(), getMostFrequentTransactionsResponse.getDescription()) &&
                Objects.equals(getCorporateRefNo(), getMostFrequentTransactionsResponse.getCorporateRefNo()) &&
                Objects.equals(getTransactionStatusId(), getMostFrequentTransactionsResponse.getTransactionStatusId()) &&
                Objects.equals(getTransactionTypeId(), getMostFrequentTransactionsResponse.getTransactionTypeId()) &&
                Objects.equals(getPaymentInstruction(), getMostFrequentTransactionsResponse.getPaymentInstruction()) &&
                Objects.equals(getAccountName(), getMostFrequentTransactionsResponse.getAccountName()) &&
                Objects.equals(getBeneficiaryName(), getMostFrequentTransactionsResponse.getBeneficiaryName()) &&
                Objects.equals(getTransactionCount(), getMostFrequentTransactionsResponse.getTransactionCount());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getDate(),
                getPaymentMethodId(),
                getSourceAccountId(),
                getBenericiaryId(),
                getAmount(),
                getDescription(),
                getCorporateRefNo(),
                getTransactionStatusId(),
                getTransactionTypeId(),
                getPaymentInstruction(),
                getAccountName(),
                getBeneficiaryName(),
                getTransactionCount());
    }
}
