/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.showcase.elite.accountsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetOverallTransactionsResponse implements Serializable {


    @ColumnAlias("total_transactions")
    private Long totalTransactions;

    @ColumnAlias("total_value")
    private BigInteger totalValue;

    public Long getTotalTransactions() {
        return this.totalTransactions;
    }

    public void setTotalTransactions(Long totalTransactions) {
        this.totalTransactions = totalTransactions;
    }

    public BigInteger getTotalValue() {
        return this.totalValue;
    }

    public void setTotalValue(BigInteger totalValue) {
        this.totalValue = totalValue;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetOverallTransactionsResponse)) return false;
        final GetOverallTransactionsResponse getOverallTransactionsResponse = (GetOverallTransactionsResponse) o;
        return Objects.equals(getTotalTransactions(), getOverallTransactionsResponse.getTotalTransactions()) &&
                Objects.equals(getTotalValue(), getOverallTransactionsResponse.getTotalValue());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTotalTransactions(),
                getTotalValue());
    }
}
