/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.showcase.elite.accountsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetTotalAccountBalanceForCorporateResponse implements Serializable {


    @ColumnAlias("totalBalance")
    private BigInteger totalBalance;

    public BigInteger getTotalBalance() {
        return this.totalBalance;
    }

    public void setTotalBalance(BigInteger totalBalance) {
        this.totalBalance = totalBalance;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetTotalAccountBalanceForCorporateResponse)) return false;
        final GetTotalAccountBalanceForCorporateResponse getTotalAccountBalanceForCorporateResponse = (GetTotalAccountBalanceForCorporateResponse) o;
        return Objects.equals(getTotalBalance(), getTotalAccountBalanceForCorporateResponse.getTotalBalance());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTotalBalance());
    }
}
