/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.showcase.elite.accountsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetTotalTransactionsResponse implements Serializable {


    @ColumnAlias("status")
    private String status;

    @ColumnAlias("total")
    private Long total;

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getTotal() {
        return this.total;
    }

    public void setTotal(Long total) {
        this.total = total;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetTotalTransactionsResponse)) return false;
        final GetTotalTransactionsResponse getTotalTransactionsResponse = (GetTotalTransactionsResponse) o;
        return Objects.equals(getStatus(), getTotalTransactionsResponse.getStatus()) &&
                Objects.equals(getTotal(), getTotalTransactionsResponse.getTotal());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStatus(),
                getTotal());
    }
}
