/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.showcase.elite.accountsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetUserByEmailResponse implements Serializable {


    @ColumnAlias("id")
    private Long id;

    @ColumnAlias("name")
    private String name;

    @ColumnAlias("profile_pic")
    private String profilePic;

    @ColumnAlias("username")
    private String username;

    @ColumnAlias("password")
    private String password;

    @ColumnAlias("corporate_id")
    private Long corporateId;

    @ColumnAlias("email")
    private String email;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getProfilePic() {
        return this.profilePic;
    }

    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Long getCorporateId() {
        return this.corporateId;
    }

    public void setCorporateId(Long corporateId) {
        this.corporateId = corporateId;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetUserByEmailResponse)) return false;
        final GetUserByEmailResponse getUserByEmailResponse = (GetUserByEmailResponse) o;
        return Objects.equals(getId(), getUserByEmailResponse.getId()) &&
                Objects.equals(getName(), getUserByEmailResponse.getName()) &&
                Objects.equals(getProfilePic(), getUserByEmailResponse.getProfilePic()) &&
                Objects.equals(getUsername(), getUserByEmailResponse.getUsername()) &&
                Objects.equals(getPassword(), getUserByEmailResponse.getPassword()) &&
                Objects.equals(getCorporateId(), getUserByEmailResponse.getCorporateId()) &&
                Objects.equals(getEmail(), getUserByEmailResponse.getEmail());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName(),
                getProfilePic(),
                getUsername(),
                getPassword(),
                getCorporateId(),
                getEmail());
    }
}
